# ============================================================
#  DORA Metrics Project — Configuration
# ============================================================

paths:
  raw_data:     data/raw/
  cleaned_data: data/cleaned/
  models:       models/
  outputs:      outputs/

files:
  jira:          jira_status_history.csv
  commits:       gitlab_commits.csv
  pipelines:     gitlab_pipelines.csv
  jobs:          gitlab_jobs.csv
  merge_requests: gitlab_merge_requests.csv

projects:
  - name: Mobile Web Banking
    key:  MBC
  - name: Data Lake
    key:  DL
  - name: Cross Sell Credit
    key:  CSCCP25
  - name: Refonte Indicateurs
    key:  RIDIDP25

workflow_order:
  - In Analysis
  - To Do
  - In Process
  - Blocked
  - In Review
  - Correction Post Review
  - Ready For Test
  - QA In Process
  - Correction Post QA
  - To Be Deployed

status_category:
  To Do:                 "To Do"
  In Analysis:           "In Progress"
  In Process:            "In Progress"
  Blocked:               "In Progress"
  In Review:             "In Progress"
  Correction Post Review:"In Progress"
  Ready For Test:        "In Progress"
  QA In Process:         "In Progress"
  Correction Post QA:    "In Progress"
  To Be Deployed:        "Done"

date_format: "%d/%m/%Y %H:%M"
